services:
  app:
    build: .
    env_file: .env.local
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"

  mongodb:
    image: mongo:7
    ports:
      - "${MONGODB_PORT}:27017"
